### ISSUE TITLE
Issue Title: Error When Creating a New Product - 500 Internal Server Error

### ISSUE THREAD

**Issue by Reyechev** [Reyechev/Medusa-Custom#1]
Description: When trying to create a new product through the Medusa admin panel, a 500 Internal Server Error is returned. The request fails despite all required fields being populated, and the product is not added to the database.

**Comment by rustdevlabs** [comment]
Suggested Fix:

Ensure the product schema is up to date with the latest migrations.
Run the database migrations manually:

      medusa migrations run

Verify that all necessary columns (e.g., product_id) are present in the database.

Additional Notes:

The issue might have been introduced after the last update to the Medusa core.
No issues were observed when creating products using the API directly (via POST request).

**Comment by Reyechev** [comment]
issue fixed thanks

**Comment by Reyechev** [comment]
Well done 0xcrypto
